# Generated by Django 6.0.1 on 2026-06-12 12:08

import django.db.models.deletion
import django.utils.timezone
import tracking.fields
import tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=200, verbose_name='entreprise')),
                ('poste', models.CharField(max_length=200, verbose_name='poste')),
                ('source', models.CharField(choices=[('france_travail', 'France Travail'), ('apec', 'APEC'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('monster', 'Monster'), ('cadremploi', 'Cadremploi'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='source')),
                ('url_offre', models.URLField(blank=True, verbose_name="URL de l'offre")),
                ('date_envoi', models.DateField(default=django.utils.timezone.localdate, verbose_name="date d'envoi")),
                ('canal_envoi', models.CharField(choices=[('email', 'Email direct'), ('formulaire', 'Formulaire site'), ('easy_apply', 'LinkedIn Easy Apply'), ('cooptation', 'Cooptation'), ('autre', 'Autre')], default='email', max_length=20, verbose_name="canal d'envoi")),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('relancee', 'Relancée'), ('entretien_planifie', 'Entretien planifié'), ('entretien_passe', 'Entretien passé'), ('refus', 'Refus'), ('offre', 'Offre reçue'), ('sans_reponse', 'Sans réponse'), ('abandonnee', 'Abandonnée')], default='envoyee', max_length=20, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['-date_envoi', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('entreprise', models.CharField(blank=True, max_length=200, verbose_name='entreprise')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('file', models.FileField(upload_to=tracking.models.cv_upload_path, verbose_name='fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='identifiant')),
                ('password', tracking.fields.EncryptedCharField(blank=True, default='', verbose_name='mot de passe')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL du logo')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='site par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "site d'emploi",
                'verbose_name_plural': "sites d'emploi",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('type', models.CharField(choices=[('telephone', 'Téléphone'), ('visio', 'Visio'), ('presentiel', 'Présentiel')], default='visio', max_length=20, verbose_name='type')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='tracking.candidature', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'entretien',
                'verbose_name_plural': 'entretiens',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='candidature',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='tracking.jobsite', verbose_name='site'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField(verbose_name='date prévue')),
                ('effectuee', models.BooleanField(default=False, verbose_name='effectuée')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tracking.candidature', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'relance',
                'verbose_name_plural': 'relances',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('relancee', 'Relancée'), ('entretien_planifie', 'Entretien planifié'), ('entretien_passe', 'Entretien passé'), ('refus', 'Refus'), ('offre', 'Offre reçue'), ('sans_reponse', 'Sans réponse'), ('abandonnee', 'Abandonnée')], max_length=20, verbose_name='statut')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tracking.candidature', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'historique de statut',
                'verbose_name_plural': 'historiques de statut',
                'ordering': ['-date'],
            },
        ),
    ]
