# Generated by Django 6.0.1 on 2026-06-12 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_builtin_site_logos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='date_envoi',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name="date d'envoi"),
        ),
    ]
