# Generated by Django 6.0.1 on 2026-06-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_candidature_date_envoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='acceptation',
            field=models.BooleanField(default=False, verbose_name='acceptation'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_entretien_1',
            field=models.DateField(blank=True, null=True, verbose_name='date entretien 1'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_entretien_2',
            field=models.DateField(blank=True, null=True, verbose_name='date entretien 2'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_entretien_3',
            field=models.DateField(blank=True, null=True, verbose_name='date entretien 3'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='entretien_programme',
            field=models.BooleanField(default=False, verbose_name='entretien programmé'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='envoyee',
            field=models.BooleanField(default=False, verbose_name='candidature envoyée'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='libelle',
            field=models.CharField(blank=True, max_length=200, verbose_name='libellé'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='offre_soumise',
            field=models.BooleanField(default=False, verbose_name='offre soumise'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='salaire_propose',
            field=models.CharField(blank=True, max_length=100, verbose_name='salaire proposé'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='traitee',
            field=models.BooleanField(default=False, verbose_name='candidature traitée'),
        ),
    ]
