# Generated by Django 6.0.1 on 2026-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_candidature_acceptation_candidature_date_entretien_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='entreprise',
            field=models.CharField(blank=True, max_length=200, verbose_name='entreprise'),
        ),
    ]
