# Generated by Django 6.0.1 on 2026-06-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_candidature_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='motif_cloture',
            field=models.CharField(blank=True, choices=[('poste_pourvu', 'Poste pourvu'), ('pas_qualifie', 'Pas assez qualifié'), ('refus_candidat', 'Refus candidat'), ('non_adequation', 'Non adéquation du poste'), ('refus_salaire', 'Refus salaire')], max_length=20, verbose_name='motif de clôture'),
        ),
    ]
