# Generated by Django 6.0.1 on 2026-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_candidature_motif_cloture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='jeton')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='libellé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'jeton API',
                'verbose_name_plural': 'jetons API',
                'ordering': ['-created_at'],
            },
        ),
    ]
