# Generated by Django 6.0.1 on 2026-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='canal_envoi',
            field=models.CharField(choices=[('email', '✉️ Email direct'), ('formulaire', '📝 Formulaire site'), ('easy_apply', '⚡ LinkedIn Easy Apply'), ('cooptation', '🤝 Cooptation'), ('autre', '🌐 Autre')], default='email', max_length=20, verbose_name="canal d'envoi"),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='motif_cloture',
            field=models.CharField(blank=True, choices=[('poste_pourvu', '🚫 Poste pourvu'), ('pas_qualifie', '📉 Pas assez qualifié'), ('refus_candidat', '🙅 Refus candidat'), ('non_adequation', '🧭 Non adéquation du poste'), ('refus_salaire', '💸 Refus salaire')], max_length=20, verbose_name='motif de clôture'),
        ),
    ]
