# Generated by Django 6.0.1 on 2026-06-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_seed_known_jobsites'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsite',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
