# Generated by Django 6.0.1 on 2026-06-14 06:46

import tracking.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_alter_candidature_canal_envoi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', tracking.fields.EncryptedCharField(blank=True, default='', verbose_name='clé API Gemini')),
                ('model', models.CharField(default='gemini-2.0-flash', max_length=100, verbose_name='modèle')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuration IA',
                'verbose_name_plural': 'configuration IA',
            },
        ),
    ]
