# Generated by Django 6.0.1 on 2026-06-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_aiconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='model',
            field=models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash — rapide et économique (recommandé)'), ('gemini-2.5-pro', 'Gemini 2.5 Pro — plus puissant'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite — le plus rapide'), ('gemini-2.0-flash', 'Gemini 2.0 Flash')], default='gemini-2.5-flash', max_length=100, verbose_name='modèle'),
        ),
    ]
