# Generated by Django 6.0.1 on 2026-06-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_aiconfig_mistral'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', '🔵 Google Gemini'), ('mistral', '🟠 Mistral AI')], max_length=10, verbose_name='fournisseur')),
                ('model', models.CharField(max_length=100, verbose_name='modèle')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='tokens entrée')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='tokens sortie')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='tokens total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'consommation IA',
                'verbose_name_plural': 'consommations IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='gemini_monthly_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='limite mensuelle Gemini (tokens)'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='mistral_monthly_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='limite mensuelle Mistral (tokens)'),
        ),
    ]
