# Generated by Django 6.0.1 on 2026-06-14 08:03

import tracking.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_aiusage_aiconfig_gemini_monthly_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='anthropic_api_key',
            field=tracking.fields.EncryptedCharField(blank=True, default='', verbose_name='clé API Anthropic'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='anthropic_model',
            field=models.CharField(choices=[('claude-haiku-4-5', 'Claude Haiku 4.5 — rapide et économique (recommandé)'), ('claude-sonnet-4-6', 'Claude Sonnet 4.6 — équilibré'), ('claude-opus-4-8', 'Claude Opus 4.8 — le plus puissant')], default='claude-haiku-4-5', max_length=100, verbose_name='modèle Anthropic'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='anthropic_monthly_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='limite mensuelle Anthropic (tokens)'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='openai_api_key',
            field=tracking.fields.EncryptedCharField(blank=True, default='', verbose_name='clé API OpenAI'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='openai_model',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o mini — rapide et économique (recommandé)'), ('gpt-4o', 'GPT-4o — plus puissant'), ('gpt-4.1-mini', 'GPT-4.1 mini')], default='gpt-4o-mini', max_length=100, verbose_name='modèle OpenAI'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='openai_monthly_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='limite mensuelle OpenAI (tokens)'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='perplexity_api_key',
            field=tracking.fields.EncryptedCharField(blank=True, default='', verbose_name='clé API Perplexity'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='perplexity_model',
            field=models.CharField(choices=[('sonar', 'Sonar — rapide (recommandé)'), ('sonar-pro', 'Sonar Pro — plus puissant')], default='sonar', max_length=100, verbose_name='modèle Perplexity'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='perplexity_monthly_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='limite mensuelle Perplexity (tokens)'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('gemini', '🔵 Google Gemini'), ('mistral', '🟠 Mistral AI'), ('openai', '🟢 OpenAI (ChatGPT)'), ('anthropic', '🟣 Anthropic (Claude)'), ('perplexity', '🔎 Perplexity')], default='gemini', max_length=10, verbose_name='fournisseur'),
        ),
        migrations.AlterField(
            model_name='aiusage',
            name='provider',
            field=models.CharField(choices=[('gemini', '🔵 Google Gemini'), ('mistral', '🟠 Mistral AI'), ('openai', '🟢 OpenAI (ChatGPT)'), ('anthropic', '🟣 Anthropic (Claude)'), ('perplexity', '🔎 Perplexity')], max_length=10, verbose_name='fournisseur'),
        ),
    ]
