# Generated by Django 6.0.1 on 2026-06-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_aiconfig_anthropic_api_key_aiconfig_anthropic_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsite',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jobsite',
            name='username',
        ),
    ]
