# Generated by Django 6.0.1 on 2026-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_remove_jobsite_password_remove_jobsite_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='analysis',
            field=models.JSONField(blank=True, default=dict, verbose_name='analyse IA'),
        ),
        migrations.AddField(
            model_name='cv',
            name='analysis_error',
            field=models.CharField(blank=True, max_length=300, verbose_name="erreur d'analyse"),
        ),
        migrations.AddField(
            model_name='cv',
            name='analysis_model',
            field=models.CharField(blank=True, max_length=100, verbose_name="modèle de l'analyse"),
        ),
        migrations.AddField(
            model_name='cv',
            name='analysis_provider',
            field=models.CharField(blank=True, max_length=10, verbose_name="fournisseur de l'analyse"),
        ),
        migrations.AddField(
            model_name='cv',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='analysé le'),
        ),
    ]
