# Generated by Django 6.0.1 on 2026-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_cv_analysis_cv_analysis_error_cv_analysis_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
