# Generated by Django 6.0.1 on 2026-06-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_cv_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='tracking.cv', verbose_name='CV'),
        ),
    ]
