# Generated by Django 6.0.1 on 2026-06-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_candidature_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='localisation',
            field=models.CharField(blank=True, max_length=200, verbose_name='localisation'),
        ),
        migrations.AddField(
            model_name='cv',
            name='par_defaut',
            field=models.BooleanField(default=False, verbose_name='CV par défaut'),
        ),
    ]
