# Generated by Django 6.0.1 on 2026-06-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_candidature_source_jobsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='site',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='tracking.jobsite', verbose_name='source'),
        ),
    ]
