# Generated by Django 6.0.1 on 2026-06-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_remove_candidature_site_alter_candidature_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidature',
            name='libelle',
        ),
        migrations.AddField(
            model_name='jobsite',
            name='type',
            field=models.CharField(choices=[('generaliste', 'Généraliste'), ('esn', 'ESN'), ('direct', 'Direct')], default='generaliste', max_length=20, verbose_name='type'),
        ),
    ]
