# Generated by Django 6.0.1 on 2026-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0025_remove_candidature_libelle_jobsite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='envoyee',
            field=models.BooleanField(default=False, verbose_name='candidature envoyée/reçue'),
        ),
    ]
