# Generated by Django 6.0.1 on 2026-06-16 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0026_alter_candidature_envoyee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('experience_index', models.PositiveIntegerField(blank=True, null=True, verbose_name='expérience associée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='tracking.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'référence',
                'verbose_name_plural': 'références',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
