# Generated by Django 6.0.1 on 2026-06-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0027_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='poste',
            field=models.CharField(blank=True, max_length=150, verbose_name='poste'),
        ),
    ]
