# Generated by Django 6.0.1 on 2026-06-25 06:47

import tracking.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0027_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_jours', models.PositiveIntegerField(default=10, verbose_name='délai avant rappel (jours)')),
                ('gmail_email', models.EmailField(blank=True, max_length=254, verbose_name="adresse Gmail d'envoi")),
                ('gmail_app_password', tracking.fields.EncryptedCharField(blank=True, default='', verbose_name="mot de passe d'application Gmail")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuration des relances',
                'verbose_name_plural': 'configuration des relances',
            },
        ),
    ]
